package main

import (
	"bufio"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	// Regexes to detect env variables
	scanRegexes = []*regexp.Regexp{
		// JS/TS process.env.KEY
		regexp.MustCompile(`\bprocess\.env\.([a-zA-Z_][a-zA-Z0-9_]*)\b`),
		// JS/TS process.env['KEY'] or process.env["KEY"]
		regexp.MustCompile(`\bprocess\.env\[['"]([a-zA-Z_][a-zA-Z0-9_]*)['"]\]`),
		// Python os.environ['KEY'] or os.environ["KEY"]
		regexp.MustCompile(`\bos\.environ\[['"]([a-zA-Z_][a-zA-Z0-9_]*)['"]\]`),
		// Python os.environ.get('KEY') or os.environ.get("KEY")
		regexp.MustCompile(`\bos\.environ\.get\(['"]([a-zA-Z_][a-zA-Z0-9_]*)['"]`),
		// Python os.getenv('KEY') or os.getenv("KEY")
		regexp.MustCompile(`\bos\.getenv\(['"]([a-zA-Z_][a-zA-Z0-9_]*)['"]`),
		// Python getenv('KEY') or getenv("KEY")
		regexp.MustCompile(`\bgetenv\(['"]([a-zA-Z_][a-zA-Z0-9_]*)['"]`),
	}
)

// ScanProject walks through the directory, scans files, and returns a sorted list of unique env keys found.
func ScanProject(root string, excludes []string) ([]string, error) {
	keysMap := make(map[string]bool)

	// Build exclude map for O(1) checks
	excludeMap := make(map[string]bool)
	for _, e := range excludes {
		excludeMap[strings.TrimSpace(e)] = true
	}

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// Check if directory should be skipped
		if d.IsDir() {
			name := d.Name()
			if excludeMap[name] || strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			return nil
		}

		// Check file extension
		ext := strings.ToLower(filepath.Ext(path))
		if ext == ".js" || ext == ".jsx" || ext == ".ts" || ext == ".tsx" || ext == ".py" || ext == ".mjs" || ext == ".cjs" {
			fileKeys, err := scanFile(path)
			if err != nil {
				// Log error but continue scanning other files
				fmt.Fprintf(os.Stderr, "Warning: failed to scan file %s: %v\n", path, err)
				return nil
			}
			for _, k := range fileKeys {
				keysMap[k] = true
			}
		}

		return nil
	})

	if err != nil {
		return nil, err
	}

	// Convert map to sorted slice
	var keys []string
	for k := range keysMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	return keys, nil
}

func scanFile(path string) ([]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var keys []string
	scanner := bufio.NewScanner(file)
	// Set larger buffer limit just in case of very long lines
	const maxCapacity = 1024 * 1024 // 1MB
	buf := make([]byte, 0, 64*1024)
	scanner.Buffer(buf, maxCapacity)

	for scanner.Scan() {
		line := scanner.Text()
		for _, re := range scanRegexes {
			matches := re.FindAllStringSubmatch(line, -1)
			for _, m := range matches {
				if len(m) > 1 && m[1] != "" {
					keys = append(keys, m[1])
				}
			}
		}
	}

	return keys, scanner.Err()
}

// GenerateExampleFile creates or updates an example file with the scanned keys.
// It parses the existing file to preserve any type definitions, comments, optional statuses, etc.
func GenerateExampleFile(outputPath string, scannedKeys []string) (int, error) {
	existingVars := make(map[string]*EnvVar)
	var orderedKeys []string

	// If file exists, parse it to preserve comments
	if _, err := os.Stat(outputPath); err == nil {
		parsed, err := ParseEnvFile(outputPath)
		if err == nil {
			existingVars = parsed
			// We can preserve the ordering of existing keys too
			// First, read lines to get exact order
			file, err := os.Open(outputPath)
			if err == nil {
				scanner := bufio.NewScanner(file)
				for scanner.Scan() {
					line := strings.TrimSpace(scanner.Text())
					if line == "" || strings.HasPrefix(line, "#") {
						continue
					}
					if strings.HasPrefix(line, "export ") {
						line = strings.TrimPrefix(line, "export ")
						line = strings.TrimSpace(line)
					}
					parts := strings.SplitN(line, "=", 2)
					if len(parts) >= 2 {
						k := strings.TrimSpace(parts[0])
						orderedKeys = append(orderedKeys, k)
					}
				}
				file.Close()
			}
		}
	}

	// Find scanned keys that are missing in the existing file
	newKeysCount := 0
	scannedKeysMap := make(map[string]bool)
	for _, k := range scannedKeys {
		scannedKeysMap[k] = true
		if _, exists := existingVars[k]; !exists {
			orderedKeys = append(orderedKeys, k)
			existingVars[k] = &EnvVar{Key: k}
			newKeysCount++
		}
	}

	// Write back to the file
	file, err := os.Create(outputPath)
	if err != nil {
		return 0, err
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	writer.WriteString("# Generated by envsentry\n# Define types using trailing comments, e.g. PORT=8080 # type:int\n\n")

	for _, key := range orderedKeys {
		v := existingVars[key]
		line := fmt.Sprintf("%s=%s", v.Key, v.DefaultValue)
		if v.Comment != "" {
			line = fmt.Sprintf("%s %s", line, v.Comment)
		} else {
			// Add placeholder hint if it's a new key
			if _, exists := scannedKeysMap[key]; exists && v.DefaultValue == "" {
				// we can write a comment hint
				line = fmt.Sprintf("%s= # type:string", v.Key)
			}
		}
		_, err = writer.WriteString(line + "\n")
		if err != nil {
			return 0, err
		}
	}

	err = writer.Flush()
	if err != nil {
		return 0, err
	}

	return newKeysCount, nil
}
