package main

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func TestScanProject(t *testing.T) {
	// Create temporary directory for mock project
	tmpDir, err := os.MkdirTemp("", "envguard-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Create directories to ignore
	os.Mkdir(filepath.Join(tmpDir, "node_modules"), 0755)
	os.Mkdir(filepath.Join(tmpDir, ".git"), 0755)

	// Write mock JS file
	jsContent := `
		const port = process.env.PORT || 3000;
		const db = process.env["DATABASE_URL"];
		const debug = process.env['DEBUG'];
		console.log(process.env.UNDEFINED_VAR);
	`
	err = os.WriteFile(filepath.Join(tmpDir, "app.js"), []byte(jsContent), 0644)
	if err != nil {
		t.Fatalf("failed to write mock JS file: %v", err)
	}

	// Write mock JS file in node_modules (should be ignored)
	err = os.WriteFile(filepath.Join(tmpDir, "node_modules", "ignored.js"), []byte("const x = process.env.IGNORED_VAR"), 0644)
	if err != nil {
		t.Fatalf("failed to write ignored JS file: %v", err)
	}

	// Write mock Python file
	pyContent := `
import os
port = os.getenv("PORT", 8000)
secret = os.environ.get('API_SECRET')
old_key = os.environ["OLD_KEY"]
another = getenv('OTHER_VAR')
`
	err = os.WriteFile(filepath.Join(tmpDir, "main.py"), []byte(pyContent), 0644)
	if err != nil {
		t.Fatalf("failed to write mock Python file: %v", err)
	}

	// Run scanner
	excludes := []string{"node_modules", ".git"}
	keys, err := ScanProject(tmpDir, excludes)
	if err != nil {
		t.Fatalf("ScanProject failed: %v", err)
	}

	expectedKeys := []string{
		"API_SECRET",
		"DATABASE_URL",
		"DEBUG",
		"OLD_KEY",
		"OTHER_VAR",
		"PORT",
		"UNDEFINED_VAR",
	}

	if !reflect.DeepEqual(keys, expectedKeys) {
		t.Errorf("expected keys %v, got %v", expectedKeys, keys)
	}
}

func TestGenerateExampleFile(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "envguard-test-gen-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	examplePath := filepath.Join(tmpDir, ".env.example")

	// 1. Initial generation
	scannedKeys := []string{"PORT", "DATABASE_URL"}
	newCount, err := GenerateExampleFile(examplePath, scannedKeys)
	if err != nil {
		t.Fatalf("GenerateExampleFile failed: %v", err)
	}
	if newCount != 2 {
		t.Errorf("expected 2 new keys, got %d", newCount)
	}

	// Verify file was created
	vars, err := ParseEnvFile(examplePath)
	if err != nil {
		t.Fatalf("ParseEnvFile failed: %v", err)
	}
	if _, ok := vars["PORT"]; !ok {
		t.Error("expected PORT in generated file")
	}
	if _, ok := vars["DATABASE_URL"]; !ok {
		t.Error("expected DATABASE_URL in generated file")
	}

	// 2. Add some comments to examplePath manually
	contentWithComments := `
# Generated by envguard
PORT=8080 # type:int
DATABASE_URL= # type:url # optional
`
	err = os.WriteFile(examplePath, []byte(contentWithComments), 0644)
	if err != nil {
		t.Fatalf("failed to write comments to mock example: %v", err)
	}

	// 3. Scan again and add a new key "NEW_KEY"
	scannedKeys = []string{"PORT", "DATABASE_URL", "NEW_KEY"}
	newCount, err = GenerateExampleFile(examplePath, scannedKeys)
	if err != nil {
		t.Fatalf("GenerateExampleFile failed on merge: %v", err)
	}
	if newCount != 1 {
		t.Errorf("expected 1 new key, got %d", newCount)
	}

	// Verify existing metadata is preserved and new key is added
	vars, err = ParseEnvFile(examplePath)
	if err != nil {
		t.Fatalf("ParseEnvFile failed after merge: %v", err)
	}

	portVar := vars["PORT"]
	if portVar.Type != "int" || portVar.DefaultValue != "8080" {
		t.Errorf("PORT metadata not preserved: %+v", portVar)
	}

	dbVar := vars["DATABASE_URL"]
	if dbVar.Type != "url" || !dbVar.Optional {
		t.Errorf("DATABASE_URL metadata not preserved: %+v", dbVar)
	}

	if _, ok := vars["NEW_KEY"]; !ok {
		t.Error("expected NEW_KEY to be added to file")
	}
}
